baseurl = "https://michaelspets.github.io/blog/"
languageCode = "en-us"
title = "Today I Learned"
theme = "hyde-x"
disqusShortname = "mspets-todayilearned"
googleAnalytics = "UA-81152217-1"

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 2

[taxonomies]
tag = "tags"
category = "categories"

[params]
highlight = "zenburn"
home = "Home"
github = "https://github.com/michaelspets"
rss = true
